using GoveeController.Domain.Devices;

namespace GoveeController.Domain.Shortcuts;

/// <summary>
/// A user-defined preset ("shortcut") that captures a power/brightness/color combination and
/// applies it to one or more devices at once, so it can be re-applied with a single click —
/// analogous to a saved scene in the Govee Home app, but defined and stored entirely within this
/// application.
/// </summary>
public sealed class Shortcut
{
    /// <summary>Primary key. Generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>User-chosen display name for the shortcut (e.g. "Movie Mode", "Reading").</summary>
    public required string Name { get; set; }

    /// <summary>The devices this shortcut applies its settings to. Must contain at least one target.</summary>
    public List<ShortcutTarget> Targets { get; set; } = [];

    /// <summary>Power state to apply.</summary>
    public required bool PowerOn { get; set; }

    /// <summary>Brightness to apply (1-100), or null to leave brightness unchanged.</summary>
    public int? Brightness { get; set; }

    /// <summary>RGB color to apply, packed as 0xRRGGBB, or null to leave color unchanged. Mutually exclusive with <see cref="ColorTemperatureKelvin"/>.</summary>
    public int? ColorRgbPacked { get; set; }

    /// <summary>White color temperature (Kelvin) to apply, or null to leave it unchanged. Mutually exclusive with <see cref="ColorRgbPacked"/>.</summary>
    public int? ColorTemperatureKelvin { get; set; }

    /// <summary>UTC timestamp when the shortcut was created, for display/ordering purposes.</summary>
    public DateTime CreatedAtUtc { get; set; }
}
