using GoveeController.Domain.Devices;

namespace GoveeController.Domain.Shortcuts;

/// <summary>
/// One device targeted by a <see cref="Shortcut"/>. A shortcut applies the same power/brightness/
/// color settings to every one of its targets, so multiple bulbs can be controlled as a group with
/// a single click (e.g. all six "Family Room" lights at once).
/// </summary>
public sealed class ShortcutTarget
{
    /// <summary>Primary key. Generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>Foreign key back to the owning <see cref="Shortcut"/>.</summary>
    public int ShortcutId { get; set; }

    /// <summary>The Govee product model of the target device. See <see cref="Device.Sku"/>.</summary>
    public required string DeviceSku { get; set; }

    /// <summary>The target device's unique identifier. See <see cref="Device.Id"/>.</summary>
    public required string DeviceId { get; set; }
}
