using GoveeController.Domain.Devices;

namespace GoveeController.Domain.Shortcuts;

/// <summary>
/// A user-defined preset ("shortcut") that captures a power/brightness/color combination and
/// applies it to one or more devices at once, so it can be re-applied with a single click —
/// analogous to a saved scene in the Govee Home app, but defined and stored entirely within this
/// application.
/// </summary>
public sealed class Shortcut
{
    /// <summary>Primary key. Generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>User-chosen display name for the shortcut (e.g. "Movie Mode", "Reading").</summary>
    public required string Name { get; set; }

    /// <summary>
    /// The devices this shortcut applies its settings to. Must contain at least one target, unless
    /// this is a composite shortcut (see <see cref="ReferencedShortcuts"/>). A shortcut has targets
    /// XOR referenced shortcuts, never both.
    /// </summary>
    public List<ShortcutTarget> Targets { get; set; } = [];

    /// <summary>
    /// Shortcuts to run as part of this composite shortcut, in order. Only meaningful (and non-empty)
    /// when this shortcut has no <see cref="Targets"/> — a shortcut is either device-targeted or
    /// composite, never both. Each referenced shortcut runs in full (including its own chain) before
    /// the next one starts, after waiting its configured delay.
    /// </summary>
    public List<ShortcutReference> ReferencedShortcuts { get; set; } = [];

    /// <summary>Power state to apply.</summary>
    public required bool PowerOn { get; set; }

    /// <summary>Brightness to apply (1-100), or null to leave brightness unchanged.</summary>
    public int? Brightness { get; set; }

    /// <summary>RGB color to apply, packed as 0xRRGGBB, or null to leave color unchanged. Mutually exclusive with <see cref="ColorTemperatureKelvin"/>.</summary>
    public int? ColorRgbPacked { get; set; }

    /// <summary>White color temperature (Kelvin) to apply, or null to leave it unchanged. Mutually exclusive with <see cref="ColorRgbPacked"/>.</summary>
    public int? ColorTemperatureKelvin { get; set; }

    /// <summary>UTC timestamp when the shortcut was created, for display/ordering purposes.</summary>
    public DateTime CreatedAtUtc { get; set; }

    /// <summary>
    /// Id of the shortcut to run after this one, or null if this shortcut ends its chain. A shortcut
    /// may be the follower of at most one other shortcut (enforced by a unique index), so chains are
    /// simple linear paths of at most 3 shortcuts. Deliberately a plain FK with no navigation
    /// property — the UI resolves names from the already-loaded shortcut list, and the service walks
    /// chains in memory (see LINKED-SHORTCUTS-PLAN.md §3.4).
    /// </summary>
    public int? NextShortcutId { get; set; }

    /// <summary>
    /// Seconds to wait after applying this shortcut before applying <see cref="NextShortcutId"/>.
    /// Ignored (and meaningless) when <see cref="NextShortcutId"/> is null. 0 means run immediately.
    /// </summary>
    public int NextShortcutDelaySeconds { get; set; }
}
