namespace GoveeController.Domain.Shortcuts;

/// <summary>
/// One shortcut referenced by a composite <see cref="Shortcut"/>. A composite shortcut has no
/// device targets of its own; instead it references other shortcuts and runs them in sequence.
/// Each referenced shortcut runs in full (including its own chain) before the next one starts,
/// after waiting its configured delay. See <see cref="Shortcut.ReferencedShortcuts"/>.
/// </summary>
public sealed class ShortcutReference
{
    /// <summary>Primary key. Generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>Foreign key back to the owning <see cref="Shortcut"/>.</summary>
    public int ShortcutId { get; set; }

    /// <summary>
    /// Foreign key to the referenced <see cref="Shortcut"/>, or null when the referenced shortcut
    /// has since been deleted (OnDelete SetNull leaves the link broken rather than deleting this
    /// composite). Deliberately a plain FK with no navigation property — the UI resolves names from
    /// the already-loaded shortcut list, and the service walks references in memory (same style as
    /// <see cref="Shortcut.NextShortcutId"/>).
    /// </summary>
    public int? ReferencedShortcutId { get; set; }

    /// <summary>
    /// Seconds to wait after the previous referenced shortcut finishes before running this one.
    /// 0 means run immediately. Validated by the service to be within 0–60.
    /// </summary>
    public int DelaySeconds { get; set; }

    /// <summary>
    /// Position of this reference within its shortcut's sequence, 0-based. Referenced shortcuts run
    /// in <see cref="Order"/> order, so the sequence the user chose is preserved by the database
    /// rather than being inferred from insertion order.
    /// </summary>
    public int Order { get; set; }
}
