using System.Threading.RateLimiting;
using GoveeController.Application.Devices;
using GoveeController.Application.Shortcuts;
using GoveeController.Infrastructure.Govee;
using GoveeController.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Polly;
using Polly.RateLimiting;

namespace GoveeController.Infrastructure;

/// <summary>
/// Composition helper that wires every Infrastructure-layer implementation to its Application-layer
/// interface. Called once from the Web layer's Program.cs, which is the only place in the solution
/// that is allowed to know about both layers at once.
/// </summary>
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Registers the Govee HTTP client (with standard retry/backoff resilience for 429/5xx), the
    /// SQLite-backed shortcut repository, in-memory caching, and the Application-layer use-case
    /// services that depend on them.
    /// </summary>
    /// <param name="services">The DI container to register into.</param>
    /// <param name="configuration">
    /// App configuration. Expects a "Govee:ApiKey" value (populated via the GOVEE_API_KEY environment
    /// variable) and a "ConnectionStrings:ShortcutsDb" value (the SQLite file path/connection string).
    /// </param>
    public static IServiceCollection AddGoveeInfrastructure(this IServiceCollection services, IConfiguration configuration)
    {
        services.AddMemoryCache();

        // ValidateOnStart makes a missing API key a startup failure — visible immediately in
        // `docker logs` — rather than an app that looks healthy but fails on every single request
        // with a generic Govee error the user has to reverse-engineer the cause of.
        services.AddOptions<GoveeApiOptions>()
            .Bind(configuration.GetSection(GoveeApiOptions.SectionName))
            .Validate(o => !string.IsNullOrWhiteSpace(o.ApiKey),
                "Govee API key is not configured. Set the GOVEE_API_KEY environment variable — see README.")
            .ValidateOnStart();

        var goveeHttpClientBuilder = services.AddHttpClient<IGoveeApiClient, GoveeApiClient>();
        goveeHttpClientBuilder.AddStandardResilienceHandler();

        // Govee's Cloud API allows ~30 requests/minute per account. The standard resilience
        // handler's own rate limiter is a concurrency limiter (effectively unlimited for this
        // workload) and its retry strategy actively *adds* requests on a 429 — it can deepen a
        // rate-limit hole rather than dig out of it. Added after AddStandardResilienceHandler so it
        // sits innermost, closest to the transport: every actual network attempt is gated,
        // including ones generated by that handler's own retries.
        //
        // One SlidingWindowRateLimiter instance is shared by every request through this handler
        // (it must be — a limiter created per-request wouldn't limit anything). 25/min leaves
        // headroom under Govee's ~30/min so normal jitter doesn't tip into a real 429 from Govee.
        var goveeRateLimiter = new SlidingWindowRateLimiter(new SlidingWindowRateLimiterOptions
        {
            PermitLimit = 25,
            Window = TimeSpan.FromMinutes(1),
            SegmentsPerWindow = 6,
            QueueLimit = 5,
            QueueProcessingOrder = QueueProcessingOrder.OldestFirst
        });
        goveeHttpClientBuilder.AddResilienceHandler("govee-client-rate-limit", builder =>
        {
            builder.AddRateLimiter(new RateLimiterStrategyOptions
            {
                RateLimiter = args => goveeRateLimiter.AcquireAsync(permitCount: 1, args.Context.CancellationToken)
            });
        });

        var connectionString = configuration.GetConnectionString("ShortcutsDb") ?? "Data Source=shortcuts.db";
        services.AddDbContext<AppDbContext>(options => options.UseSqlite(connectionString));

        services.AddScoped<IShortcutRepository, ShortcutRepository>();
        services.AddScoped<IDeviceControlService, DeviceControlService>();
        services.AddScoped<IShortcutService, ShortcutService>();

        return services;
    }
}
