using GoveeController.Domain.Shortcuts;

namespace GoveeController.Domain.Schedules;

/// <summary>
/// A rule that automatically applies a saved <see cref="Shortcut"/> at a specific local
/// wall-clock time, either recurring on one or more days of the week or once on a specific date.
/// Fired by the background runner (see GoveeController.Infrastructure's
/// <c>ScheduleRunnerService</c>) rather than by user interaction.
/// </summary>
public sealed class Schedule
{
    /// <summary>Primary key. Generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>
    /// Id of the <see cref="Shortcut"/> this schedule applies. Deliberately a plain FK with no
    /// navigation property, matching <see cref="Shortcut.NextShortcutId"/>'s style — the UI
    /// resolves the name from an already-loaded shortcut list.
    /// </summary>
    public required int ShortcutId { get; set; }

    /// <summary>
    /// Which days of the week this schedule recurs on. <see cref="ScheduleDays.None"/> means this
    /// is a one-time schedule instead (see <see cref="OneTimeDateLocal"/>) — the two are mutually
    /// exclusive and exactly one must be set, enforced by <c>ScheduleService</c>, not by this type.
    /// </summary>
    public ScheduleDays DaysOfWeekMask { get; set; }

    /// <summary>
    /// The single local date this schedule fires on, for a one-time schedule. Null for a recurring
    /// schedule (<see cref="DaysOfWeekMask"/> non-<see cref="ScheduleDays.None"/>).
    /// </summary>
    public DateOnly? OneTimeDateLocal { get; set; }

    /// <summary>Local wall-clock time of day this schedule fires at, in both modes.</summary>
    public required TimeOnly TimeOfDayLocal { get; set; }

    /// <summary>
    /// Whether this schedule is active. A disabled schedule is never picked up by the runner and
    /// has a null <see cref="NextRunAtUtc"/>.
    /// </summary>
    public bool IsEnabled { get; set; } = true;

    /// <summary>
    /// The next UTC instant this schedule is due to fire, or null while disabled or (for a
    /// one-time schedule) after it has already fired — one-time schedules are deleted once they
    /// fire, so in practice this is only ever null here while disabled. Recomputed by
    /// <c>ScheduleService</c> on every create, edit, enable, and after each run — see
    /// SCHEDULED-SHORTCUTS-PLAN.md §3.3 for why this is stored rather than derived per tick.
    /// </summary>
    public DateTime? NextRunAtUtc { get; set; }

    /// <summary>UTC timestamp when the schedule was created, for display/ordering purposes.</summary>
    public DateTime CreatedAtUtc { get; set; }
}
