// <auto-generated />
using System;
using GoveeController.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoveeController.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803164145_AddCompositeShortcuts")]
    partial class AddCompositeShortcuts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GoveeController.Domain.Schedules.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysOfWeekMask")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("OneTimeDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShortcutId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("TimeOfDayLocal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextRunAtUtc");

                    b.HasIndex("ShortcutId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("GoveeController.Domain.Shortcuts.Shortcut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Brightness")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorRgbPacked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorTemperatureKelvin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextShortcutDelaySeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("NextShortcutId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PowerOn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextShortcutId")
                        .IsUnique();

                    b.ToTable("Shortcuts");
                });

            modelBuilder.Entity("GoveeController.Domain.Shortcuts.ShortcutReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelaySeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReferencedShortcutId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShortcutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReferencedShortcutId");

                    b.HasIndex("ShortcutId");

                    b.ToTable("ShortcutReference");
                });

            modelBuilder.Entity("GoveeController.Domain.Shortcuts.ShortcutTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShortcutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShortcutId");

                    b.ToTable("ShortcutTarget");
                });

            modelBuilder.Entity("GoveeController.Domain.Schedules.Schedule", b =>
                {
                    b.HasOne("GoveeController.Domain.Shortcuts.Shortcut", null)
                        .WithMany()
                        .HasForeignKey("ShortcutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoveeController.Domain.Shortcuts.Shortcut", b =>
                {
                    b.HasOne("GoveeController.Domain.Shortcuts.Shortcut", null)
                        .WithMany()
                        .HasForeignKey("NextShortcutId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GoveeController.Domain.Shortcuts.ShortcutReference", b =>
                {
                    b.HasOne("GoveeController.Domain.Shortcuts.Shortcut", null)
                        .WithMany()
                        .HasForeignKey("ReferencedShortcutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GoveeController.Domain.Shortcuts.Shortcut", null)
                        .WithMany("ReferencedShortcuts")
                        .HasForeignKey("ShortcutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoveeController.Domain.Shortcuts.ShortcutTarget", b =>
                {
                    b.HasOne("GoveeController.Domain.Shortcuts.Shortcut", null)
                        .WithMany("Targets")
                        .HasForeignKey("ShortcutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoveeController.Domain.Shortcuts.Shortcut", b =>
                {
                    b.Navigation("ReferencedShortcuts");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
